Fix line endings, coding style and module auto-loading (#15)
* style: Normalize line endings

As remarked in pull request #13 there were Windows vs. Linux line ending
mismatches in the C sources.

The expected way to solve this is to store the files with Linux line
endings and have Git auto-convert them for Windows:
git config core.autocrlf true # on Windows
git config core.autocrlf input # on Linux

Add a .gitattributes file to enforce treating text files this way.

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Fix trailing whitespace

Remove any trailing whitespace flagged in the previous commit's diff.

Signed-off-by: Andreas Färber <afaerber@suse.com>

* Fix typo in comment

"modifyied" -> "modified"

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Adjust parenthesis spacing to kernel coding style

Fixes multiple scripts/checkpatch.pl errors:
ERROR: space prohibited after that open parenthesis '('
ERROR: space prohibited before that close parenthesis ')'

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Adjust argument spacing after comma

Resolves multiple checkpatch.pl errors:
ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Adjust space around :

Resolves checkpatch.pl error:
ERROR: spaces required around that ':' (ctx:WxV)

Still unresolved:
WARNING: use of in_atomic() is incorrect outside core kernel code

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Fix suspect conditional indentation

Fix indentation of goto line.
Resolves checkpatch.pl warning:

WARNING: suspect code indent for conditional statements (8, 8)
+	if( ret )
+        goto err_pci_reg_drv;

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Adjust indentation to kernel coding style

Resolves multiple checkpatch.pl issues:
ERROR: code indent should use tabs where possible
ERROR: that open brace { should be on the previous line
WARNING: please, no spaces at the start of a line

While at it, drop one white line.

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Insert white lines after variable declarations

Resolves checkpatch.pl warnings:
WARNING: Missing a blank line after declarations

White at it, drop one white line after switch.

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Avoid zero-initialization of static variables

Resolves three checkpatch.pl errors:
ERROR: do not initialise statics to 0

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Do not try to emit error message when out of memory

Resolves checkpatch.pl warning:
WARNING: Possible unnecessary 'out of memory' message

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Avoid braces

Resolves checkpatch.pl warning:
WARNING: braces {} are not necessary for single statement blocks

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Make struct file_operations const

Resolves checkpatch.pl warning:
WARNING: struct file_operations should normally be const

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Make struct kobj_type const

Resolves checkpatch.pl warnings:
WARNING: struct kobj_type should normally be const

While at it, also make them static since not used elsewhere.

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Avoid in_atomic()

The kzalloc()s are happening at probe time and won't be in atomic context.

Resolves two checkpatch.pl warnings:
WARNING: use of in_atomic() is incorrect outside core kernel code

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Avoid NULL-check for kfree()

Resolves checkpatch.pl warnings:
WARNING: braces {} are not necessary for single statement blocks
WARNING: kfree(NULL) is safe and this check is probably not required

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Adjust SPDX comment style

Resolves checkpatch.pl warnings:
WARNING: Improper SPDX comment style for 'src/cdadrv.h', please use '/*' instead
WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
WARNING: Improper SPDX comment style for 'src/cdadrv.h', please use '/*' instead
WARNING: Missing or malformed SPDX-License-Identifier tag in line 1

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Drop semicolon at end of macro

The callers were all using a semicolon already.

Resolves checkpatch.pl warnings:
WARNING: macros should not use a trailing semicolon

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Add missing static

Drop unnecessary predeclarations and make the functions static.

Resolves multiple checkpatch.pl warnings:
WARNING: externs should be avoided in .c files

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Avoid unsigned

Resolves checkpatch.pl warnings:
WARNING: Prefer 'unsigned int' to bare use of 'unsigned'

Signed-off-by: Andreas Färber <afaerber@suse.com>

* style: Avoid assignment in if

Resolves checkpatch.pl errors:
ERROR: do not use assignment in if condition

Signed-off-by: Andreas Färber <afaerber@suse.com>

* Tidy up module-level printk()

Commit 0cec081abee506cceba7e254c295f9ac277eaa64 had started getting rid
of plain printk() in device code.

Replace remaining printk() in test_probe code path by pr_info().

Resolves checkpatch.pl warnings:
WARNING: printk() should include KERN_<LEVEL> facility level

While at it, define a prefix to clarify where the output is from.

Signed-off-by: Andreas Färber <afaerber@suse.com>

* Tidy up last remaining printk()

Uncomment for build-testing and convert to dev_dbg().

Signed-off-by: Andreas Färber <afaerber@suse.com>

* Fix the PCI device ID table

Add missing MODULE_DEVICE_TABLE(pci, ...) to auto-load the kernel module
without systemd load-modules.d workarounds.

PCI_DEVICE(0, 0) does not fully zero-terminate the cda_pci_ids array,
as reported by MODULE_DEVICE_TABLE().

Drop cdapci.conf but keep uninstalling it from previous installations.

Signed-off-by: Andreas Färber <afaerber@suse.com>

* Tidy up dynamic PCI ID handling

Instead of modifying the static device ID table, use pci_add_dynid().

Note that another existing mechanism is:
echo vvvv dddd > /sys/bus/pci/drivers/cda/new_id

Signed-off-by: Andreas Färber <afaerber@suse.com>

---------

Signed-off-by: Andreas Färber <afaerber@suse.com>